name: in_app_purchase
description: A Flutter plugin for in-app purchases. Exposes APIs for making in-app purchases through the App Store and Google Play.
homepage: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase
version: 0.3.4+6

dependencies:
  async: ^2.4.2
  collection: ^1.14.13
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^3.4.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  in_app_purchase_example:
    path: example/
  test: ^1.5.2
  shared_preferences: ^0.5.10
  integration_test:
    path: ../integration_test
  pedantic: ^1.8.0

#dependency_overrides:
#  build_resolvers: ^1.3.11

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.inapppurchase
        pluginClass: InAppPurchasePlugin
      ios:
        pluginClass: InAppPurchasePlugin

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
