name: in_app_purchase
description: A Flutter plugin for in-app purchases. Exposes APIs for making in-app purchases through the App Store and Google Play.
author:  Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase
version: 0.2.1+3


dependencies:
  async: ^2.3.0
  collection: ^1.14.12
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  meta: ^1.1.7

dev_dependencies:
  build_runner: ^1.7.1
  json_serializable: ^3.2.2
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  in_app_purchase_example:
    path: example/
  test: ^1.6.10
  shared_preferences: ^0.5.3+4

dependency_overrides:
  test_api: ^0.2.7
  collection: ^1.14.12

flutter:
  plugin:
    androidPackage: io.flutter.plugins.inapppurchase
    pluginClass: InAppPurchasePlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"
